### ISSUE TITLE
Persistence when restarting

### ISSUE THREAD

**Issue by ChevronTango** [exposr/exposr-cli#13]
If the client is set to automatically create an account (because none was specified) then this account ID is held in memory. If, for whatever reason, the client then restarts then this account ID is lost and the new client tries to connect with the same tunnel-id, but new account name, which causes a failure and the client is unable to ever recover. This should also apply if the tunnel-id was also generated automatically.

**Comment by fredriklindberg** [comment]
Server version 0.9.0 supports single-node persistence through SQLite. Adding persistence in the client would add unnecessary complexity.
